### ISSUE TITLE
sauce key配置问题

### ISSUE THREAD

**Issue by xuexb** [mipengine/mip#197]
### 问题:

由于在 <https://github.com/mipengine/mip/blob/master/.travis.yml#L18> 名文配置了 key, 再加上 sauce 服务一个github帐号只能对应一个邮箱, 不然生成的 build status img 就不准了, 我自己也测了下确实, 如: 我 fork 了 mip, 随便改改在自己仓库就可以编译, 并且这个编译状态将直接影响 `mipengine/mip@msater` 的编译状态.

### 解决方案:

- 在 http://saucelabs.com 上重置下 key
- 使用 <https://docs.travis-ci.com/user/encryption-keys/> 把 key 加密了
- 在`.travis.yml`里使用

```
addons:
  sauce_connect:
    username: sauce帐号id
  jwt:
    secure: 加密后的secure
```

---

经我多次测试, 只在 https://travis-ci.com 里`repo/settings`里配的`Environment Variables`会在别人PR时不生效, 因为密钥是保护的~ 必须使用`addons.jwt.secure`方式才行~ 这个事坑了我好几天!!! <https://github.com/sentsin/layui/commit/943a2767c1168aed7cee4e4d7938202ae5708526>
